name: tests
on:
  push:
    tags-ignore:
      - '[0-9]+.[0-9]+.[0-9]+'
    branches:
      - master
      - review/**
    paths:
      - 'code/**'
      - 'Makefile'
      - 'misc/CMakeLists.txt'
  pull_request:
    branches:
      - master
    paths:
      - 'code/**'
      - 'Makefile'
      - 'misc/CMakeLists.txt'

jobs:
  prep:
    name: Notify about testing
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Release')"
    steps:
      - uses: inlife/actiord-action@v1
        with:
          url: ${{ secrets.ACTIORD_URL }}
          icon: https://avatars1.githubusercontent.com/u/26773913?s=200&v=4
          state: started

  build-win:
    name: Test Windows
    runs-on: windows-latest
    needs: [prep]
    steps:
      - uses: actions/checkout@v1
      - name: Run cmake generator
        run: mkdir build ; cd build ; cmake ../misc
      - name: Run Windows build
        run: cd build ; cmake --build .
      - name: Run unit tests
        run: cd build ; .\Debug\unit.exe

  build-lin:
    name: Test Linux
    runs-on: ubuntu-latest
    needs: [prep]
    steps:
      - uses: actions/checkout@v1
      - name: Run build on Linux
        run: make test
      - name: Run optimized build on Linux
        run: LEVEL=-O3 make test

  build-mac:
    name: Test macOS
    runs-on: macOS-latest
    needs: [prep]
    steps:
      - uses: actions/checkout@v1
      - name: Run build on macOS
        run: make test
      - name: Run optimized build on macOS
        run: LEVEL=-O3 make test

  done:
    name: Notify about status
    runs-on: ubuntu-latest
    needs: [build-mac, build-lin, build-win]
    if: "!contains(github.event.head_commit.message, 'Release')"
    steps:
      - uses: inlife/actiord-action@v1
        if: ${{ contains(needs.build-mac.result, 'success') && contains(needs.build-lin.result, 'success') && contains(needs.build-win.result, 'success') }}
        with:
          url: ${{ secrets.ACTIORD_URL }}
          icon: https://avatars1.githubusercontent.com/u/26773913?s=200&v=4
          state: succeeded

      - uses: inlife/actiord-action@v1
        if: ${{ !(contains(needs.build-mac.result, 'success') && contains(needs.build-lin.result, 'success') && contains(needs.build-win.result, 'success')) }}
        with:
          url: ${{ secrets.ACTIORD_URL }}
          icon: https://avatars1.githubusercontent.com/u/26773913?s=200&v=4
          state: failed
